version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hotell-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: HotelBooking
      MYSQL_USER: hotelluser
      MYSQL_PASSWORD: hotellpass
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
